# Generated by Django 4.0.6 on 2022-11-07 07:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('main_image', models.FileField(null=True, upload_to='about_us', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('main_text', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('delivery_packages', models.IntegerField()),
                ('countries_covered', models.IntegerField()),
                ('happy_clients', models.IntegerField()),
                ('tons_of_good', models.IntegerField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('blog_image', models.FileField(null=True, upload_to='blog_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('sub_image1', models.FileField(null=True, upload_to='blog_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('sub_image2', models.FileField(null=True, upload_to='blog_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('highlighted_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoModelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(max_length=50, null=True)),
                ('test', models.BooleanField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='CourierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Configuration',
                'verbose_name_plural': 'FAQ Configurations',
            },
        ),
        migrations.CreateModel(
            name='OverviewBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=50)),
                ('banner_image', models.FileField(null=True, upload_to='banner', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
            ],
            options={
                'verbose_name': 'Banner Model',
                'verbose_name_plural': 'Banner Models',
            },
        ),
        migrations.CreateModel(
            name='PackageDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('package_name', models.CharField(blank=True, max_length=150, null=True)),
                ('total_weight', models.FloatField()),
                ('total_quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('grand_total', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=50, null=True)),
                ('airport', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('tag_name', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=150)),
                ('main_service_image', models.FileField(null=True, upload_to='service', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('first_text', models.CharField(max_length=150)),
                ('first_description', models.TextField()),
                ('second_text', models.CharField(max_length=150)),
                ('second_description', models.TextField()),
                ('second_service_image', models.FileField(null=True, upload_to='service', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('third_text', models.CharField(max_length=150)),
                ('third_description', models.TextField()),
                ('third_service_image', models.FileField(null=True, upload_to='service', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ShipperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('hotel', models.CharField(max_length=150, null=True)),
                ('room_no', models.IntegerField()),
                ('passpord_number', models.CharField(max_length=50, null=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('site_name', models.CharField(max_length=30)),
                ('logo_image', models.FileField(null=True, upload_to='logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('mode', models.CharField(choices=[('Live', 'Live'), ('Down', 'Down'), ('Maintainance', 'Maintainance')], default='Live', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('favicon', models.FileField(null=True, upload_to='logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Setting',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('fb_url', models.URLField(blank=True, max_length=100, null=True)),
                ('insta_url', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('tiktok_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Setting',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_image', models.FileField(null=True, upload_to='teams_pic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('designation', models.CharField(max_length=50)),
                ('fb_url', models.URLField(blank=True, max_length=100, null=True)),
                ('insta_url', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('tiktok_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Teams Setting',
                'verbose_name_plural': 'Teams Setting',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('user_image', models.FileField(null=True, upload_to='user_img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('user_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='TrackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('tracking_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tracking Code')),
            ],
            options={
                'verbose_name': 'Tracking Model',
                'verbose_name_plural': 'Tracking Models',
            },
        ),
        migrations.CreateModel(
            name='TrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.FileField(null=True, upload_to='profile_pic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'gif'])])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Other', 'Other')], default='Cash', max_length=20)),
                ('is_picked_up', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.cargomodelpackage', verbose_name='Cargo Details')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.couriermodel', verbose_name='Courier')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.deliverymode', verbose_name='Delivery Mode')),
                ('package_details', models.ManyToManyField(to='backend_cargo.packagedetailsmodel', verbose_name='Related Packages')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.receivermodel', verbose_name='Receiver Details')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.shippermodel', verbose_name='Shipper Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GetQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city_departure', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('type_freight', models.CharField(blank=True, choices=[('Express Delivery', 'Express Delivery'), ('Ocean Freight', 'Ocean Freight'), ('Road Freight', 'Road Freight'), ('Air Freight', 'Air Freight')], max_length=50, null=True)),
                ('flight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.couriermodel', verbose_name='Type of Carrier')),
            ],
            options={
                'verbose_name': 'GetQuote',
                'verbose_name_plural': 'GetQuotes',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('creater_name', models.CharField(blank=True, max_length=50, null=True)),
                ('creater_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.blogmodel', verbose_name='Blog Info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
