# Generated by Django 4.0.6 on 2022-09-16 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('main_image', models.FileField(null=True, upload_to='about_us', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('main_text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('delivery_packages', models.IntegerField()),
                ('countries_covered', models.IntegerField()),
                ('happy_clients', models.IntegerField()),
                ('tons_of_good', models.IntegerField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('blog_image', models.FileField(null=True, upload_to='banner', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('blog_image2', models.FileField(null=True, upload_to='banner', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('crreated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Configuration',
                'verbose_name_plural': 'FAQ Configurations',
            },
        ),
        migrations.CreateModel(
            name='OverviewBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=50)),
                ('banner_image', models.FileField(null=True, upload_to='banner', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
            ],
            options={
                'verbose_name': 'Banner Model',
                'verbose_name_plural': 'Banner Models',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('tag_name', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('main_service_image', models.FileField(null=True, upload_to='service', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('first_text', models.CharField(max_length=100)),
                ('first_description', models.TextField()),
                ('second_text', models.CharField(max_length=100)),
                ('second_description', models.TextField()),
                ('third_text', models.CharField(max_length=100)),
                ('third_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30)),
                ('logo_image', models.FileField(null=True, upload_to='logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('contact_email', models.EmailField(max_length=254)),
                ('mode', models.CharField(choices=[('Live', 'Live'), ('Down', 'Down'), ('Maintainance', 'Maintainance')], default='Live', max_length=20)),
                ('favicon', models.FileField(null=True, upload_to='logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('fb_url', models.URLField(blank=True, max_length=100, null=True)),
                ('insta_url', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('tiktok_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Setting',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('user_image', models.FileField(null=True, upload_to='user_img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('user_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='TrackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.PositiveIntegerField(verbose_name='Tracking Code')),
            ],
            options={
                'verbose_name': 'Tracking Model',
                'verbose_name_plural': 'Tracking Models',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('creater_name', models.CharField(blank=True, max_length=50, null=True)),
                ('creater_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.blogmodel', verbose_name='Blog Info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
