# Generated by Django 4.0.6 on 2022-11-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmodel',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_details_cargo', to='backend_cargo.packagemodel', verbose_name='Package Details'),
        ),
        migrations.AddField(
            model_name='trackingmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.trackingstatus', verbose_name='Tracking Status'),
        ),
    ]
