# Generated by Django 4.0.6 on 2022-09-16 21:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_cargo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='crreated_by',
            new_name='created_by',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.FileField(null=True, upload_to='profile_pic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.png'])])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
