# Generated by Django 4.0.6 on 2022-11-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cargo', '0002_trackingmodel_package_trackingmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingmodel',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
