# Generated by Django 4.0.6 on 2022-12-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cargo', '0003_trackingmodel_description_trackingmodel_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getquote',
            old_name='city',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='type_freight',
        ),
    ]
