# Generated by Django 4.0.6 on 2022-12-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cargo', '0004_rename_city_getquote_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getquote',
            name='flight_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_cargo.couriermodel', verbose_name='Type of Carrier'),
        ),
    ]
