# Generated by Django 4.0.6 on 2023-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cargo', '0006_ecommerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerce',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='weight',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
