# Generated by Django 4.0.6 on 2023-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cargo', '0007_ecommerce_brand_ecommerce_color_ecommerce_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerce',
            name='actual_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
